version: '3.1'

services:

  db:
    image: mysql:8.3
    container_name: mysql_test
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test123
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    restart: always
    networks:
      - task-backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - task-backend

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_test
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
        - 5673:5673
        - 15673:15673
    networks:
      - task-backend

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 5 --reload
    volumes:
      - ../:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - rabbitmq
    networks:
      - task-backend


networks:
  task-backend:
    driver: bridge
